import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GraphContextProvider from "./contexts/GraphContext";
import IndexedDbContextProvider from "./contexts/IndexedDbContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex items-center overflow-hidden py-20 flex-col px-16 dark w-screen min-h-screen overflow-y-auto`}
			>
				<IndexedDbContextProvider>
					<GraphContextProvider>{children}</GraphContextProvider>
				</IndexedDbContextProvider>
			</body>
		</html>
	);
}
